# Generated by Django 4.2.7 on 2023-11-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
